spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cache:
    redis:
      host: localhost
      port: 6379
      time-to-live: 60000
      cache-null-values: false
  datasource:
    url: jdbc:postgresql://localhost:5432/tb_veiculo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 10000
      pool-name: vehiclePoolConnection
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true